enum TopSpeakerActionTypes {
    CREATE_TOP_SPEAKER = "CREATE_TOP_SPEAKER",
    GET_TOP_SPEAKER = "GET_TOP_SPEAKER",
    GET_ALL_TOP_SPEAKER = "GET_ALL_TOP_SPEAKER",
    SET_TOP_SPEAKER = "GET_TOP_SPEAKER",
    SET_TOP_SPEAKER_ERROR = "SET_TOP_SPEAKER_ERROR",
    UPDATE_TOP_SPEAKER = "UPDATE_TOP_SPEAKER",
    DELETE_TOP_SPEAKER = "DELETE_TOP_SPEAKER",
}

export default TopSpeakerActionTypes;
