enum ApplicationActionTypes {

  GET_APPLICATION = "GET_APPLICATION",
  GET_ALL_APPLICATION = "GET_ALL_APPLICATION",
  GET_ARCHIVE_APPLICATION = "GET_ARCHIVE_APPLICATION",
  UPDATE_APPLICATION = "UPDATE_APPLICATION",

}

export default ApplicationActionTypes;
