enum ContactUsActionTypes {
    GET_CONTACT = "GET_CONTACT",
    GET_ALL_CONTACTS = "GET_ALL_CONTACTS",
    SET_CONTACT_ID = "SET_CONTACT_ID",
    SET_CONTACT_ERROR = "SET_CONTACT_ERROR",
    GET_DELETED_CONTACTS = "GET_DELETED_CONTACTS",
    DELETE_CONTACT = "DELETE_CONTACT",
  }
  
  export default ContactUsActionTypes;
  